services:
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27034"
      MONGODB_DATABASE_NAME: "somedb"

  # MongoDB Config Server
  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27027:27027"
    volumes:
      - config-data:/data/db
    command:
      [
        "--replSet",
        "config_server",
        "--configsvr",
        "--bind_ip_all",
        "--port",
        "27027"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # Shard 1 Replica Set (3 nodes: 1 primary, 2 secondary)
  shard1a:
    image: mongo:latest
    container_name: shard1a
    restart: always
    ports:
      - "27028:27028"
    volumes:
      - shard1a-data:/data/db
    command:
      [
        "--replSet",
        "shard1rs",
        "--shardsvr",
        "--bind_ip_all",
        "--port",
        "27028"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1b:
    image: mongo:latest
    container_name: shard1b
    restart: always
    ports:
      - "27029:27029"
    volumes:
      - shard1b-data:/data/db
    command:
      [
        "--replSet",
        "shard1rs",
        "--shardsvr",
        "--bind_ip_all",
        "--port",
        "27029"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1c:
    image: mongo:latest
    container_name: shard1c
    restart: always
    ports:
      - "27030:27030"
    volumes:
      - shard1c-data:/data/db
    command:
      [
        "--replSet",
        "shard1rs",
        "--shardsvr",
        "--bind_ip_all",
        "--port",
        "27030"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # Shard 2 Replica Set (3 nodes: 1 primary, 2 secondary)
  shard2a:
    image: mongo:latest
    container_name: shard2a
    restart: always
    ports:
      - "27031:27031"
    volumes:
      - shard2a-data:/data/db
    command:
      [
        "--replSet",
        "shard2rs",
        "--shardsvr",
        "--bind_ip_all",
        "--port",
        "27031"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2b:
    image: mongo:latest
    container_name: shard2b
    restart: always
    ports:
      - "27032:27032"
    volumes:
      - shard2b-data:/data/db
    command:
      [
        "--replSet",
        "shard2rs",
        "--shardsvr",
        "--bind_ip_all",
        "--port",
        "27032"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2c:
    image: mongo:latest
    container_name: shard2c
    restart: always
    ports:
      - "27033:27033"
    volumes:
      - shard2c-data:/data/db
    command:
      [
        "--replSet",
        "shard2rs",
        "--shardsvr",
        "--bind_ip_all",
        "--port",
        "27033"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # MongoDB Router (Mongos)
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27034:27034"
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv:27027",
        "--bind_ip_all",
        "--port",
        "27034"
      ]
    depends_on:
      - configSrv
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

volumes:
  config-data:
  shard1a-data:
  shard1b-data:
  shard1c-data:
  shard2a-data:
  shard2b-data:
  shard2c-data:
